libmolgrid::ExampleProvider
std::shared_ptr<ExampleRefProvider> provider
ExampleExtractor extractor
ExampleProviderSettings init_settings
size_t last_epoch
std::shared_ptr< ExampleRefProvider > createProvider(const ExampleProviderSettings &settings)
return provider as specifyed by settings
Referenced by ExampleProvider::ExampleProvider, ExampleProvider::ExampleProvider, ExampleProvider::ExampleProvider, ExampleProvider::ExampleProvider.
ExampleProvider(const ExampleProviderSettings &settings=ExampleProviderSettings())
Create provider using default gnina typing.
ExampleProvider(const ExampleProviderSettings &settings, std::shared_ptr< AtomTyper > t)
Create provider/extractor according to settings with single typer.
ExampleProvider(const ExampleProviderSettings &settings, std::shared_ptr< AtomTyper > t1, std::shared_ptr< AtomTyper > t2)
Create provider/extractor according to settings with two typers.
ExampleProvider(const ExampleProviderSettings &settings, const std::vector< std::shared_ptr< AtomTyper > > &typrs, const std::vector< std::string > &molcaches=std::vector< std::string >())
Create provider/extractor according to settings.
ExampleProvider(std::shared_ptr< ExampleRefProvider > p, const ExampleExtractor &e)
use provided provider
virtual ~ExampleProvider()
void populate(const std::string &fname, int num_labels=-1)
load example file file fname and setup provider
void populate(const std::vector< std::string > &fnames, int num_labels=-1)
load multiple example files
virtual size_t num_labels() const
return number of labels for each example (computed from first example only)
Referenced by ExampleProvider::populate, ExampleProvider::populate.
void next(Example &ex)
provide next example
virtual Example next()
Referenced by ExampleProvider::next.
virtual size_t get_small_epoch_num() const
Return current small epoch number A small epoch occurs once every training example has been seen at MOST once. For example, when providing a balanced view of unbalanced data, a small epoch will complete once the less common class has been iterated over. Note this is the epoch of the next example to be provided, not the previous.
virtual size_t get_large_epoch_num() const
Return current large epoch number A large epoch occurs once every training example has been seen at LEAST once. For example, when providing a balanced view of unbalanced data, a large epoch will complete once the more common class has been iterated over. Note this is the epoch of the next example to be provided, not the previous.
virtual size_t small_epoch_size() const
Return number of example in small epoch.
virtual size_t large_epoch_size() const
Return number of example in large epoch.
virtual void reset()
Reset to beginning.
void skip(unsigned n)
skip over the first n examples
const ExampleProviderSettings & settings() const
return settings created with
Referenced by ExampleProvider::createProvider, ExampleProvider::ExampleProvider, ExampleProvider::ExampleProvider, ExampleProvider::ExampleProvider, ExampleProvider::ExampleProvider.
void next_batch(std::vector< Example > &ex, unsigned batch_size=0)
provide a batch of examples
Referenced by ExampleProvider::next_batch.
virtual std::vector< Example > next_batch(unsigned batch_size=0)
provide a batch of examples, unspecified or 0 batch_size uses default batch size
bool at_new_epoch()
return true if we have crossed into a new epoch (or are about to) Note that once this returns true once, it won't again until the next epoch has been consumed.
ExampleExtractor & get_extractor()
ExampleRefProvider & get_provider()
size_t num_types() const
number of types
std::vector< std::string > get_type_names() const
names of types (requires explicit typing)
size_t size() const
return number of examples
void save_mem_caches(std::ostream &out) const
Write out current contents of memory caches to provided output stream.
out output stream
void save_mem_caches(const std::string &fname) const
Write out current contents of memory caches to provided file.
fname file name
void load_mem_caches(std::istream &in)
Read contents of input stream into memory caches.
in input stream
void load_mem_caches(const std::string &fname)
Read contents of provided file into memory caches.
fname file name
size_t mem_caches_size() const