libmolgrid::Quaternion
typedef float fl
fl a
Referenced by Quaternion::conj, Quaternion::inverse, Quaternion::norm, Quaternion::operator*, Quaternion::operator*=, Quaternion::operator/, Quaternion::operator/, Quaternion::operator/=, Quaternion::operator==, Quaternion::Quaternion, Quaternion::Quaternion, Quaternion::R_component_1.
fl b
Referenced by Quaternion::conj, Quaternion::inverse, Quaternion::norm, Quaternion::operator*, Quaternion::operator*=, Quaternion::operator/, Quaternion::operator/, Quaternion::operator/=, Quaternion::operator==, Quaternion::Quaternion, Quaternion::Quaternion, Quaternion::R_component_2.
fl c
Referenced by Quaternion::conj, Quaternion::inverse, Quaternion::norm, Quaternion::operator*, Quaternion::operator*=, Quaternion::operator/, Quaternion::operator/, Quaternion::operator/=, Quaternion::operator==, Quaternion::Quaternion, Quaternion::Quaternion, Quaternion::R_component_3.
fl d
Referenced by Quaternion::conj, Quaternion::inverse, Quaternion::norm, Quaternion::operator*, Quaternion::operator*=, Quaternion::operator/, Quaternion::operator/, Quaternion::operator/=, Quaternion::operator==, Quaternion::Quaternion, Quaternion::Quaternion, Quaternion::R_component_4.
CUDA_CALLABLE_MEMBER Quaternion()
Referenced by Quaternion::conj, Quaternion::inverse, Quaternion::operator*, Quaternion::operator*=, Quaternion::operator*=, Quaternion::operator/, Quaternion::operator/, Quaternion::operator/=, Quaternion::operator/=, Quaternion::operator==, Quaternion::rotate.
CUDA_CALLABLE_MEMBER Quaternion(fl A, fl B, fl C, fl D)
Construct quaternion with real then unreal components.
CUDA_CALLABLE_MEMBER fl R_component_1() const
Return the real or scalar part.
Referenced by Quaternion::operator*, Quaternion::operator/, Quaternion::real.
CUDA_CALLABLE_MEMBER fl R_component_2() const
Return unreal[0].
Referenced by Quaternion::operator*, Quaternion::operator/, Quaternion::rotate.
CUDA_CALLABLE_MEMBER fl R_component_3() const
Return unreal[1].
Referenced by Quaternion::operator*, Quaternion::operator/, Quaternion::rotate.
CUDA_CALLABLE_MEMBER fl R_component_4() const
Return unreal[2].
Referenced by Quaternion::operator*, Quaternion::operator/, Quaternion::rotate.
CUDA_CALLABLE_MEMBER Quaternion & operator*=(const fl &r)
In-place multiplication by scalar (element-wise).
CUDA_CALLABLE_MEMBER Quaternion & operator/=(const fl &r)
In-place division by scalar (element-wise).
CUDA_CALLABLE_MEMBER Quaternion operator/(const fl &r)
Division by scalar (element-wise).
CUDA_CALLABLE_MEMBER Quaternion operator*(const Quaternion &r) const
Quaternion multiplication.
CUDA_CALLABLE_MEMBER Quaternion & operator*=(const Quaternion &r)
Quaternion in-place multiplication.
CUDA_CALLABLE_MEMBER bool operator==(const Quaternion &r) const
check bit level equality
CUDA_CALLABLE_MEMBER Quaternion operator/(const Quaternion &r)
Quaternion divison.
CUDA_CALLABLE_MEMBER Quaternion operator/=(const Quaternion &r)
Quaternion in-place divison.
CUDA_CALLABLE_MEMBER Quaternion conj() const
Conjugate.
Referenced by Quaternion::rotate.
CUDA_CALLABLE_MEMBER float real() const
CUDA_CALLABLE_MEMBER float norm() const
The Cayley norm - the square of the Euclidean norm.
Referenced by Quaternion::rotate.
CUDA_CALLABLE_MEMBER float3 rotate(fl x, fl y, fl z) const
Rotation point (x,y,z) using this quaternion.
Referenced by Transform::backward, GridInterpolater::forward, Quaternion::transform.
CUDA_CALLABLE_MEMBER float3 transform(fl x, fl y, fl z, float3 center, float3 translate) const
Rotate around the provided center and translate.
CUDA_CALLABLE_MEMBER Quaternion inverse() const
Return inverse.
Referenced by Transform::backward, GridInterpolater::forward.