libmolgrid::ManagedGrid< Dtype, 1 >
using subgrid_t = Dtype
using base_t = ManagedGridBase<Dtype, 1>
using gpu_grid_t =
using cpu_grid_t =
using type =
friend ManagedGrid< Dtype, 2 >
friend ManagedGrid< Dtype, NumDims+1 >
gpu_grid_t gpu_grid
cpu_grid_t cpu_grid
std::shared_ptr<Dtype> cpu_ptr
size_t capacity
buffer_data* gpu_info
friend ManagedGridBase< Dtype, NumDims - 1 >
ManagedGrid()=default
Referenced by ManagedGrid< Dtype, 1 >::clone, ManagedGrid< Dtype, 1 >::load, ManagedGrid< Dtype, 1 >::ManagedGrid.
ManagedGrid(size_t sz)
Dtype & operator[](size_t i)
Dtype operator[](size_t i) const
Dtype & operator()(size_t a)
Dtype operator()(size_t a) const
ManagedGrid< Dtype, 1 > clone() const
void save(Archive &ar, const unsigned int version) const
void load(Archive &ar, const unsigned int version)
const size_t * dimensions() const
size_t dimension(size_t i) const
const size_t * offsets() const
size_t offset(size_t i) const
size_t size() const
void fill_zero()
Dtype & operator()(I... indices)
Dtype operator()(I... indices) const
size_t copyTo(cpu_grid_t &dest) const
size_t copyTo(gpu_grid_t &dest) const
size_t copyTo(ManagedGridBase< Dtype, NumDims > &dest) const
size_t copyFrom(const cpu_grid_t &src)
size_t copyFrom(const gpu_grid_t &src)
size_t copyFrom(const ManagedGridBase< Dtype, NumDims > &src)
size_t copyInto(size_t start, const ManagedGridBase< Dtype, NumDims > &src)
ManagedGrid< Dtype, NumDims > resized(I... sizes)
const gpu_grid_t & gpu() const
gpu_grid_t & gpu()
const cpu_grid_t & cpu() const
cpu_grid_t & cpu()
void togpu(bool dotransfer=true) const
void tocpu(bool dotransfer=true) const
bool ongpu() const
bool oncpu() const
operator cpu_grid_t() const
operator cpu_grid_t &()
operator gpu_grid_t() const
operator gpu_grid_t &()
const Dtype * data() const
Dtype * data()
bool operator==(const ManagedGridBase< Dtype, NumDims > &rhs) const
ManagedGrid(const ManagedGridBase< Dtype, 2 > &G, size_t i)
void alloc_and_set_cpu(size_t sz)
void clone_ptrs()
using buffer_data =
size_t N
static void delete_buffer(void *ptr)