libmolgrid::CoordCache
using MemCache = std::unordered_map<const char *, CoordinateSet>
MemCache memcache
std::shared_ptr<AtomTyper> typer
std::string data_root
std::string molcache
bool use_cache
bool addh
bool make_vector_types
protonate
boost::iostreams::mapped_file_source cache_map
convert index types to vector, will also convert to type based radii and add a dummy type
std::unordered_map<const char *, size_t> offsets
CoordCache()
CoordCache(std::shared_ptr< AtomTyper > t, const ExampleProviderSettings &settings=ExampleProviderSettings(), const std::string &mc="")
~CoordCache()
void set_coords(const char *fname, CoordinateSet &coord)
Set coord to the appropriate CoordinateSet for fname.
fname file name, not including root directory prefix, of molecular data coord CoordinateSet for passed molecule
Referenced by CoordCache::set_coords.
size_t num_types() const
return the number of types (channels) each example will have
std::vector< std::string > get_type_names() const
void save_mem_cache(std::ostream &out) const
Write out current contents of memory cache to provided output stream.
out output stream
Referenced by CoordCache::save_mem_cache, CoordCache::save_mem_cache.
void save_mem_cache(const std::string &fname) const
Write out current contents of memory cache to provided file.
fname file name
void load_mem_cache(std::istream &in)
Read contents of input stream into memory cache.
in input stream
Referenced by CoordCache::load_mem_cache, CoordCache::load_mem_cache.
void load_mem_cache(const std::string &fname)
Read contents of provided file into memory cache.
fname file name
size_t mem_cache_size() const