libmolgrid::ManagedGrid
using subgrid_t = ManagedGrid<Dtype, NumDims - 1>
using base_t = ManagedGridBase<Dtype, NumDims>
using gpu_grid_t = Grid<Dtype, NumDims, true>
using cpu_grid_t = Grid<Dtype, NumDims, false>
using type = Dtype
friend ManagedGrid< Dtype, NumDims+1 >
gpu_grid_t gpu_grid
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyInto, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGridBase< Dtype, 1 >::resized.
cpu_grid_t cpu_grid
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGrid< Dtype, 1 >::operator(), ManagedGrid< Dtype, 1 >::operator(), ManagedGridBase< Dtype, 1 >::operator(), ManagedGridBase< Dtype, 1 >::operator(), ManagedGridBase< Dtype, 1 >::resized.
std::shared_ptr<Dtype> cpu_ptr
Referenced by ManagedGridBase< Dtype, 1 >::operator==, ManagedGridBase< Dtype, 1 >::resized.
size_t capacity
Referenced by ManagedGridBase< Dtype, 1 >::resized.
buffer_data* gpu_info
Referenced by ManagedGridBase< Dtype, 1 >::resized.
friend ManagedGridBase< Dtype, NumDims - 1 >
ManagedGrid(size_t *sizes)
ManagedGrid(const ManagedGridBase< Dtype, NumDims+1 > &G, size_t i)
void alloc_and_set_cpu(size_t sz)
Referenced by ManagedGridBase< Dtype, 1 >::clone_ptrs, ManagedGridBase< Dtype, 1 >::ManagedGridBase, ManagedGridBase< Dtype, 1 >::ManagedGridBase.
void clone_ptrs()
Referenced by ManagedGrid< Dtype, 1 >::clone, ManagedGrid< Dtype, NumDims - 1 >::clone.
ManagedGrid()=default
ManagedGrid(I... sizes)
subgrid_t operator[](size_t i) const
ManagedGrid< Dtype, NumDims > clone() const
void save(Archive &ar, const unsigned int version) const
void load(Archive &ar, const unsigned int version)
const size_t * dimensions() const
size_t dimension(size_t i) const
Referenced by ManagedGrid< Dtype, 1 >::save.
const size_t * offsets() const
size_t offset(size_t i) const
Referenced by ManagedGridBase< Dtype, 1 >::copyInto.
size_t size() const
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyInto, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGrid< Dtype, 1 >::load, ManagedGrid< Dtype, NumDims - 1 >::load, ManagedGridBase< Dtype, 1 >::ManagedGridBase, ManagedGridBase< Dtype, 1 >::ManagedGridBase, ManagedGridBase< Dtype, 1 >::resized, ManagedGrid< Dtype, 1 >::save.
void fill_zero()
Dtype & operator()(I... indices)
Dtype operator()(I... indices) const
size_t copyTo(cpu_grid_t &dest) const
Referenced by ManagedGridBase< Dtype, 1 >::copyTo, ManagedGridBase< Dtype, 1 >::resized.
size_t copyTo(gpu_grid_t &dest) const
size_t copyTo(ManagedGridBase< Dtype, NumDims > &dest) const
size_t copyFrom(const cpu_grid_t &src)
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom.
size_t copyFrom(const gpu_grid_t &src)
size_t copyFrom(const ManagedGridBase< Dtype, NumDims > &src)
size_t copyInto(size_t start, const ManagedGridBase< Dtype, NumDims > &src)
ManagedGrid< Dtype, NumDims > resized(I... sizes)
const gpu_grid_t & gpu() const
Referenced by ManagedGridBase< Dtype, 1 >::operator gpu_grid_t, ManagedGridBase< Dtype, 1 >::operator gpu_grid_t &.
gpu_grid_t & gpu()
const cpu_grid_t & cpu() const
Referenced by ManagedGridBase< Dtype, 1 >::operator cpu_grid_t, ManagedGridBase< Dtype, 1 >::operator cpu_grid_t &.
cpu_grid_t & cpu()
void togpu(bool dotransfer=true) const
Referenced by ManagedGridBase< Dtype, 1 >::gpu, ManagedGridBase< Dtype, 1 >::gpu, ManagedGridBase< Dtype, 1 >::ongpu, ManagedGridBase< Dtype, 1 >::resized.
void tocpu(bool dotransfer=true) const
Referenced by ManagedGridBase< Dtype, 1 >::cpu, ManagedGridBase< Dtype, 1 >::cpu, ManagedGrid< Dtype, 1 >::operator(), ManagedGrid< Dtype, 1 >::operator(), ManagedGridBase< Dtype, 1 >::operator(), ManagedGridBase< Dtype, 1 >::operator(), ManagedGrid< Dtype, 1 >::operator[], ManagedGrid< Dtype, 1 >::operator[], ManagedGrid< Dtype, 1 >::save.
bool ongpu() const
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyFrom, ManagedGridBase< Dtype, 1 >::copyInto, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGridBase< Dtype, 1 >::copyTo, ManagedGridBase< Dtype, 1 >::fill_zero, ManagedGridBase< Dtype, 1 >::resized, ManagedGridBase< Dtype, 1 >::tocpu.
bool oncpu() const
Referenced by ManagedGridBase< Dtype, 1 >::togpu.
operator cpu_grid_t() const
operator cpu_grid_t &()
operator gpu_grid_t() const
operator gpu_grid_t &()
const Dtype * data() const
Referenced by ManagedGridBase< Dtype, 1 >::copyInto, ManagedGrid< Dtype, 1 >::load, ManagedGrid< Dtype, NumDims - 1 >::load, ManagedGrid< Dtype, 1 >::save.
Dtype * data()
bool operator==(const ManagedGridBase< Dtype, NumDims > &rhs) const
using buffer_data = mgrid_buffer_data<Dtype>
size_t N
static void delete_buffer(void *ptr)
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu.