libmolgrid
IterationScheme
LogLevel
using CartesianMGrid = CartesianGrid<ManagedGrid<float, 3> >
using cuda_float3 = ::float3
FileMappedGninaTyper defaultGninaReceptorTyper(recmap)
default types for receptor AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobe Bromine Iodine Chlorine Fluorine Nitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptor Oxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonor Sulfur SulfurAcceptor Phosphorus Calcium Zinc GenericMetal Boron Manganese Magnesium Iron
Referenced by ExampleDataset::ExampleDataset, ExampleProvider::ExampleProvider.
FileMappedGninaTyper defaultGninaLigandTyper(ligmap)
default types for ligand AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobe Bromine Iodine Chlorine Fluorine Nitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptor Oxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonor Sulfur SulfurAcceptor Phosphorus GenericMetal Boron Manganese Magnesium Zinc Calcium Iron
Referenced by ExampleDataset::ExampleDataset, ExampleProvider::ExampleProvider.
std::default_random_engine random_engine
random engine used in libmolgrid
Referenced by ReceptorStratifiedExampleRefProvider< Provider, K >::nextref, SamplingExampleRefProvider< Provider1, Provider2 >::nextref, ReceptorStratifiedExampleRefProvider< Provider, K >::setup, UniformExampleRefProvider::setup, Transform::Transform.
StringCache string_cache
Referenced by ExampleRef::ExampleRef, CoordCache::load_mem_cache, GroupedExampleRefProvider< Provider >::nextref, CoordinateSet::serialize.
unsigned do_not_optimize_away
Referenced by CoordCache::CoordCache.
BOOST_PP_REPEAT_FROM_TO(1, LIBMOLGRID_MAX_GRID_DIM, EXPAND_GRID_DEFINITIONS, 0)
CUDA_CALLABLE_MEMBER float3 cart2grid(float3 origin, float resolution, float x, float y, float z)
Referenced by GridInterpolater::forward.
CUDA_CALLABLE_MEMBER float3 grid2cart(float3 origin, float resolution, unsigned i, unsigned j, unsigned k)
Referenced by GridInterpolater::forward.
template CartesianGrid< ManagedGrid< double, 3 > > read_dx(std::istream &in)
Referenced by read_dx, read_dx, read_dx_grids.
template CartesianGrid< ManagedGrid< double, 3 > > read_dx(const std::string &fname)
read dx grid from file name
void read_dx(std::istream &in, Grid< Dtype, 3 > &grid)
Read dx formatted grid into provided grid, which must have the correct dimensions.
void read_dx(const std::string &fname, Grid< Dtype, 3 > &grid)
read dx grid from file name
void read_bin(std::istream &in, G &grid)
read in binary file, grid must be correct size
void write_dx(std::ostream &out, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale=1.0)
output grid as dx formatted file Values are multiplied by scale, which may be necessary to adjust for limited precision in the text-based format
Referenced by write_dx, write_dx_grids.
void write_dx(const std::string &fname, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale)
output dx to file name
void write_dx_grids(const std::string &prefix, const std::vector< std::string > &names, const Grid< Dtype, 4 > &grid, const float3 &center, float resolution, float scale=1.0)
Output multiple grids using type names as a suffix.
prefix filename will have form [prefix]_[typename].dx names must have same size as first dimension of grid grid input grids center resolution scale multiply each value by this factor
void read_dx_grids(const std::string &prefix, const std::vector< std::string > &names, Grid< Dtype, 4 > &grid)
Read multiple grids using type names as a suffix. Grids must be correctly sized.
prefix filename will have form [prefix]_[typename].dx names must have same size as first dimension of grid grid input grids
void write_map(std::ostream &out, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale=1.0)
output grid as autodock map formatted file
output autodock4 to stream
Referenced by write_map.
void write_map(const std::string &fname, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale)
output autodock4 to filename
void write_bin(std::ostream &out, const G &grid)
std::ostream & log(LogLevel level=INFO)
Referenced by GroupedExampleRefProvider< Provider >::addref, ReceptorStratifiedExampleRefProvider< Provider, K >::setup, ValueStratifiedExampleRefProfider< Provider >::setup.
std::string ftoa(float v)
std::string itoa(int v)
Referenced by BalancedExampleRefProvider::addref, ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu, GridMaker::backward, GroupedExampleRefProvider< Provider >::check_batch_size, Grid< Dtype, 1, isCUDA >::check_index, Grid< Dtype, NumDims-1, isCUDA >::check_index, GridMaker::check_index_args, GridMaker::check_vector_args, GridInterpolater::checkGrids, CoordinateSet::copyTo, CoordinateSet::copyTo, Example::extract_label, Example::extract_labels, GridMaker::forward, GridMaker::forward, GridMaker::forward, ExampleExtractor::get_type_names, CoordinateSet::make_vector_types, Example::merge_coordinates, Example::merge_coordinates, Example::merge_coordinates, UniformExampleRefProvider::operator[], read_dx, read_dx, read_dx_grids, read_dx_helper, CoordinateSet::sum_types, Example::sum_types, write_dx_grids.
BOOST_PP_REPEAT_FROM_TO(1, LIBMOLGRID_MAX_GRID_DIM, EXPAND_MGRID_DEFINITIONS, 0)
static stringstream recmap(R"(AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobe Bromine Iodine Chlorine Fluorine Nitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptor Oxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonor Sulfur SulfurAcceptor Phosphorus Calcium Zinc GenericMetal Boron Manganese Magnesium Iron )")
Referenced by defaultGninaLigandTyper.
static stringstream ligmap(R"(AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobe Bromine Iodine Chlorine Fluorine Nitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptor Oxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonor Sulfur SulfurAcceptor Phosphorus GenericMetal Boron Manganese Magnesium Zinc Calcium Iron )")
Referenced by defaultGninaLigandTyper.
FileMappedGninaTyper defaultGninaReceptorTyper(recmap)
FileMappedGninaTyper defaultGninaLigandTyper(ligmap)
size_t typ_vec_size(const std::vector< std::vector< float > > &t)
Referenced by CoordinateSet::CoordinateSet.
bool is_numeric(const string &number)
Referenced by ExampleRef::ExampleRef.
unsigned read_dx_helper(std::istream &in, float3 &center, float &res)
Referenced by read_dx, read_dx.
template CartesianGrid< ManagedGrid< float, 3 > > read_dx(std::istream &in)
template CartesianGrid< ManagedGrid< float, 3 > > read_dx(const std::string &fname)
template void write_dx(std::ostream &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_dx(const std::string &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_dx(std::ostream &, const Grid< double, 3 > &, const float3 &, float, float)
template void write_dx(const std::string &, const Grid< double, 3 > &, const float3 &, float, float)
template void write_dx_grids(const std::string &, const std::vector< std::string > &, const Grid< float, 4 > &, const float3 &, float, float)
template void write_dx_grids(const std::string &, const std::vector< std::string > &, const Grid< double, 4 > &, const float3 &, float, float)
template void read_dx_grids(const std::string &, const std::vector< std::string > &, Grid< float, 4 > &)
template void read_dx_grids(const std::string &, const std::vector< std::string > &, Grid< double, 4 > &)
template void write_map(std::ostream &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_map(const std::string &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_map(std::ostream &, const Grid< double, 3 > &, const float3 &, float, float)
template void write_map(const std::string &, const Grid< double, 3 > &, const float3 &, float, float)
static float sqDistance(float3 pt, float x, float y, float z)
Referenced by GridMaker::calc_point.